# use Ganache's forked mainnet mode as the default network
networks:
  default: mainnet-fork
  development:
    cmd_settings:
      accounts: 100

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    version: 0.6.8
    optimizer:
        enabled: true
        runs: 200
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"



reports:
  exclude_paths:
    - contracts/test/Token.sol
  exclude_contracts:
    - SafeMath

dev_deployment_artifacts: True
